---
- name: Install Pass
  hosts: all
  become: true

  tasks:
    - name: Install EPEL Repo
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version in [ "7", "8" ]
      ansible.builtin.include_role:
        name: geerlingguy.repo-epel

    - name: Install Pass
      ansible.builtin.include_role:
        name: "gotmax23.pass"
