---
#
# Ansible managed
#
repository:
  description: Ansible role that installs password-store (pass), the standard Unix password manager.
  homepage: https://galaxy.ansible.com/gotmax23/pass
  topics: pass, password-store, passwords, password, security, password_manager, ansible, molecule, ansible-role, role
