---
#
# Ansible managed
#
repository:
  description: Ansible role to install password-store (pass), the standard Unix password manager.
  homepage: "https://galaxy.ansible.com/gotmax23/pass"
  topics: pass, password-store, ansible, molecule, ansible-role, role
