---
- name: Generate files
  hosts: localhost
  gather_facts: false

  vars:
    generator_molecule_wflow_matrix:
      install_method: [ "distro_package", "source" ]
    generator_molecule_wflow_test_cmd:
      cmd: |
        export pass_state=present && molecule test -s single --destroy never
        export pass_state=absent && molecule test -s single
      env:
        pass_install_method: !unsafe ${{ matrix.install_method }}

  roles:
    - gotmax23.generator

# vim: set filetype=yaml.ansible:
