---
- name: Generate files
  hosts: localhost
  gather_facts: false

  vars:
    generator_molecule_wflow_test:
      env:
        pass_install_method: !unsafe ${{ matrix.install_method }}
      matrix:
        install_method: [ "distro_package", "source" ]
      skip_test_step: true
      steps:
        - name: "Molecule test: pass_state=present"
          env:
            pass_state: present
          run: molecule test -s single --destroy never
        - name: "Molecule test: pass_state=absent"
          env:
            pass_state: absent
          run: molecule test -s single --destroy never
        - name: Molecule destroy
          if: always()
          run: molecule destroy -s single


  roles:
    - gotmax23.generator

# vim: set filetype=yaml.ansible:
