---
# tasks file for pass
- name: Ensure variables are set correctly
  ansible.builtin.import_tasks: assert.yml
  delegate_to: localhost
  connection: local
  become: false

- name: "Install Pass clipboard helper"
  when: (pass_state == "present")
  ansible.builtin.package:
    name: "{{ pass_clipboard_package }}"
    state: present

- name: "{{ installw }} Pass package"
  when: pass_install_method == "distro_package"
  ansible.builtin.package:
    name: "{{ pass_package }}"
    state: "{{ pass_state }}"

- name: "{{ installw }} Pass from source"
  when: pass_install_method == "source"
  ansible.builtin.include_tasks: source_install.yml
