---
- name: Converge
  hosts: all
  become: true

  vars:
    pass_install_method: "{{ lookup('env', 'pass_install_method') | default('distro_package', True) }}"

  tasks:
    - name: Install Pass
      vars:
        pass_state: present
      ansible.builtin.import_role:
        name: "gotmax23.pass"
