---
- name: Converge
  hosts: all
  become: true

  vars:
    pass_molecule_env_vars:
      - pass_install_method
      - pass_state
      - pass_version

  tasks:
    - name: Set role variables if they are defined as env variables
      loop: "{{ pass_molecule_env_vars }}"
      when:
        - lookup('env', item) is string
        - lookup('env', item) != ""
      ansible.builtin.set_fact:
        "{{ item }}": "{{ lookup('env', item) }}"

    -
      loop: "{{ pass_molecule_env_vars }}"
      ansible.builtin.debug:
        msg: "{{ lookup('vars', item, default='') }}"

    - name: Install/Uninstall Pass
      ansible.builtin.import_role:
        name: "gotmax23.pass"
