---
- name: Prepare
  hosts: all
  become: true

  vars:
    _pass_which_package:
      Debian: debianutils
      default: which
    pass_which_package: "{{ _pass_which_package[ansible_os_family] | default(_pass_which_package['default']) }}"


  tasks:
    - name: Update apt cache
      when: ansible_pkg_mgr == "apt"
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure which is installed (needed for verify)
      ansible.builtin.package:
        name: "{{ pass_which_package }}"

    - name: Ensure epel repo is installed
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version in [ "7", "8" ]
      ansible.builtin.include_role:
        name: geerlingguy.repo-epel
