---
- name: Verify
  hosts: all

  vars:
    pass_state: "{{ lookup('env', 'pass_state') | default('present', True) }}"
    _pass_which_package:
      Debian: debianutils
      default: which
    pass_which_package: "{{ _pass_which_package[ansible_os_family] | default(_pass_which_package['default']) }}"

  tasks:
    - name: Ensure which is installed
      ansible.builtin.package:
        name: "{{ pass_which_package }}"

    - name: Check if Pass is present
      register: pass_presence
      changed_when: false
      failed_when: false
      ansible.builtin.command:
        cmd: which pass

    - name: Ensure Pass is installed
      when: pass_state == "present"
      ansible.builtin.assert:
        quiet: true
        that: pass_presence.rc == 0


    - name: Ensure Pass is uninstalled
      when: pass_state == "absent"
      ansible.builtin.assert:
        quiet: true
        that: pass_presence.rc != 0
